### ISSUE TITLE
Issue setting up Juypter notebook

### ISSUE THREAD

**Issue by tclewis29** [microsoft/acoustic-bird-detection#3]
I am attempting to run through the README, but am getting this issue in the second line of code. I am new to Python so am not sure if this is a local issue or an issue with the resources themselves.
```
(base) C:\Users\User>conda create -n birdsounds python=3.7
WARNING conda.exceptions:print_unexpected_error_report(1216): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "C:\Users\User\miniconda3\lib\site-packages\conda\cli\main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "C:\Users\User\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "C:\Users\User\miniconda3\lib\site-packages\conda\cli\main_create.py", line 21, in execute
    if is_conda_environment(context.target_prefix):
  File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 591, in target_prefix
    return determine_target_prefix(self)
  File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 1738, in determine_target_prefix
    return locate_prefix_by_name(prefix_name)
  File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 1681, in locate_prefix_by_name
    envs_dirs = context.envs_dirs
  File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 517, in envs_dirs
    return mockable_context_envs_dirs(self.root_writable, self.root_prefix, self._envs_dirs)
  File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 91, in mockable_context_envs_dirs
    fixed_dirs += join(user_data_dir(APP_NAME, APP_NAME), 'envs'),
  File "C:\Users\User\miniconda3\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
    path = os.path.join(_get_win_folder(const), appauthor, appname)
  File "C:\Users\User\miniconda3\lib\site-packages\conda\_vendor\appdirs.py", line 284, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\lib\site-packages\conda\exceptions.py", line 1214, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "C:\Users\User\miniconda3\lib\site-packages\conda\cli\main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\User\miniconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "C:\Users\User\miniconda3\lib\site-packages\conda\cli\main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "C:\Users\User\miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\User\miniconda3\lib\site-packages\conda\cli\main_create.py", line 21, in execute
        if is_conda_environment(context.target_prefix):
      File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 591, in target_prefix
        return determine_target_prefix(self)
      File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 1738, in determine_target_prefix
        return locate_prefix_by_name(prefix_name)
      File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 1681, in locate_prefix_by_name
        envs_dirs = context.envs_dirs
      File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 517, in envs_dirs
        return mockable_context_envs_dirs(self.root_writable, self.root_prefix, self._envs_dirs)
      File "C:\Users\User\miniconda3\lib\site-packages\conda\base\context.py", line 91, in mockable_context_envs_dirs
        fixed_dirs += join(user_data_dir(APP_NAME, APP_NAME), 'envs'),
      File "C:\Users\User\miniconda3\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
        path = os.path.join(_get_win_folder(const), appauthor, appname)
      File "C:\Users\User\miniconda3\lib\site-packages\conda\_vendor\appdirs.py", line 284, in _get_win_folder_with_pywin32
        from win32com.shell import shellcon, shell
    ImportError: DLL load failed while importing shell: The specified procedure could not be found.

`$ C:\Users\User\miniconda3\Scripts\conda-script.py create -n birdsounds python=3.7`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.
```

I am using Python 3.10.7 on Windows 10

**Comment by tclewis29** [comment]
Issue was not anything to do with the resources, I just had to install an older version of win32.com

```
pip install pywin32==300
```
